-- Migration: Add tagging system for item categorization
-- Creates tags table for master list and item_tags column for per-poster tags

-- Create tags table for master tag list
CREATE TABLE IF NOT EXISTS tags (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(name);

-- Add column for per-poster selected tags
ALTER TABLE posters
ADD COLUMN IF NOT EXISTS item_tags JSONB;

COMMENT ON COLUMN posters.item_tags IS 'Array of tag names selected for this poster (both AI-suggested and manually selected)';

-- Pre-populate with initial tags (excluding meta-tags like "New tag" and "Not Received")
INSERT INTO tags (name) VALUES
  ('Abstract'),
  ('Animals'),
  ('Appliances'),
  ('Aquatic & Beach'),
  ('Architecture'),
  ('Art Deco'),
  ('Art Galleries'),
  ('Art Nouveau'),
  ('Automobiles'),
  ('Aviation'),
  ('Bauhaus'),
  ('Beach'),
  ('Belle Epoque'),
  ('Bill Graham'),
  ('Birds'),
  ('Botanical'),
  ('Bullfighting'),
  ('Cabaret'),
  ('Circus'),
  ('Classic Rock'),
  ('Coca-Cola'),
  ('Collier''s'),
  ('Concerts'),
  ('Contemporary'),
  ('Cycling'),
  ('Dance'),
  ('Destinations'),
  ('Disney'),
  ('Esquire'),
  ('Expositions & Festivals'),
  ('Family Dog'),
  ('Fashion'),
  ('Film Noir'),
  ('Food & Drink'),
  ('Formula 1'),
  ('Fortune'),
  ('French Satirical Comic'),
  ('Glamour'),
  ('Grand Prix'),
  ('Holidays'),
  ('Horror'),
  ('Industry & Technology'),
  ('Insects & Butterflies'),
  ('Judge'),
  ('L''Assiette au Beurre'),
  ('La Vie Parisienne'),
  ('Le Rire'),
  ('Leslie''s'),
  ('Life Magazine'),
  ('Loterie Nationale'),
  ('Magic'),
  ('Map'),
  ('Marine Life'),
  ('Marshall Plan'),
  ('Medical & Anatomy'),
  ('Military'),
  ('Minimalism'),
  ('Modern'),
  ('Motorcycles'),
  ('Movies'),
  ('Museum'),
  ('Music'),
  ('Musicals'),
  ('Natural History'),
  ('Nautical'),
  ('Olympics'),
  ('Opera'),
  ('Pin Up'),
  ('Political'),
  ('Popular Mechanics'),
  ('Popular Science'),
  ('Products & Services'),
  ('Propaganda'),
  ('Puck'),
  ('Reptiles'),
  ('Satire'),
  ('Scenery & Landscape'),
  ('Sci Fi'),
  ('Science'),
  ('Sexploitation'),
  ('Ski'),
  ('Space & Astronomy'),
  ('Sports'),
  ('Surrealism'),
  ('The New Yorker'),
  ('Theater'),
  ('Tobacco'),
  ('Trains'),
  ('Travel & Destinations'),
  ('Weapons'),
  ('Western'),
  ('Wine'),
  ('Wissembourg'),
  ('World War 1'),
  ('World War 2'),
  ('Zoo')
ON CONFLICT (name) DO NOTHING;
