import type { CreateDealerInput } from '@/types/dealer';

/**
 * Curated list of default dealers for seeding the database.
 * Organized by reliability tier and type.
 */
export const DEFAULT_DEALERS: CreateDealerInput[] = [
  // ============================================================
  // TIER 1: Major Auction Houses (highest reliability)
  // ============================================================
  {
    name: 'Heritage Auctions',
    type: 'auction_house',
    website: 'https://www.ha.com',
    country: 'United States',
    city: 'Dallas',
    region: 'North America',
    reliabilityTier: 1,
    attributionWeight: 0.90,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.ha.com/search?q={query}',
    searchSoldUrlTemplate: 'https://www.ha.com/search?q={query}&type=sold',
    specializations: ['movie_posters', 'advertising', 'travel', 'books', 'entertainment'],
    notes: 'Largest collectibles auctioneer in the world. Excellent for movie posters and vintage advertising.',
  },
  {
    name: "Sotheby's",
    type: 'auction_house',
    website: 'https://www.sothebys.com',
    country: 'United Kingdom',
    city: 'London',
    region: 'Global',
    reliabilityTier: 1,
    attributionWeight: 0.95,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.sothebys.com/en/search?query={query}',
    specializations: ['fine_art', 'advertising', 'travel', 'books', 'prints'],
    notes: 'Premier global auction house. High-end vintage posters and fine art prints.',
  },
  {
    name: "Christie's",
    type: 'auction_house',
    website: 'https://www.christies.com',
    country: 'United Kingdom',
    city: 'London',
    region: 'Global',
    reliabilityTier: 1,
    attributionWeight: 0.95,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.christies.com/search?entry={query}',
    specializations: ['fine_art', 'advertising', 'books', 'maps', 'prints'],
    notes: 'Premier global auction house. Vintage posters, prints, and illustrated books.',
  },
  {
    name: 'Swann Auction Galleries',
    type: 'auction_house',
    website: 'https://www.swanngalleries.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 1,
    attributionWeight: 0.90,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://catalogue.swanngalleries.com/Lots/search/?searchTerm={query}',
    specializations: ['all_posters', 'advertising', 'illustration', 'books', 'maps', 'prints'],
    notes: 'Specializes in works on paper. Excellent for posters, prints, photographs, and rare books.',
  },
  {
    name: 'Bonhams',
    type: 'auction_house',
    website: 'https://www.bonhams.com',
    country: 'United Kingdom',
    city: 'London',
    region: 'Global',
    reliabilityTier: 1,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.bonhams.com/search/?q={query}',
    specializations: ['fine_art', 'entertainment', 'movie_posters', 'books'],
    notes: 'Major international auction house with strong entertainment memorabilia department.',
  },

  // ============================================================
  // TIER 2: Specialized Poster Dealers
  // ============================================================
  {
    name: 'Golden Age Posters',
    type: 'poster_dealer',
    website: 'https://www.goldenageposters.com',
    country: 'United States',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.goldenageposters.com/?s={query}',
    specializations: ['movie_posters', 'wwii', 'wwi', 'advertising', 'propaganda'],
    notes: 'Excellent source for war posters and vintage movie posters. Reliable attributions.',
  },
  {
    name: 'Posteritati',
    type: 'poster_dealer',
    website: 'https://www.posteritati.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.posteritati.com/search?q={query}',
    specializations: ['movie_posters', 'entertainment'],
    notes: 'NYC-based vintage movie poster specialist. Large inventory, excellent condition grading.',
  },
  {
    name: 'Rennert Gallery',
    type: 'poster_dealer',
    website: 'https://www.rennertgallery.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['advertising', 'art_nouveau', 'art_deco', 'french', 'travel'],
    notes: 'One of the most respected vintage poster dealers. Specializes in Art Nouveau and Art Deco.',
  },
  {
    name: 'International Poster Gallery',
    type: 'poster_dealer',
    website: 'https://www.internationalposter.com',
    country: 'United States',
    city: 'Boston',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.internationalposter.com/search/?q={query}',
    specializations: ['travel', 'advertising', 'art_deco', 'art_nouveau', 'swiss'],
    notes: 'Large inventory of travel and advertising posters. Excellent research resources.',
  },
  {
    name: 'Poster Auctions International',
    type: 'auction_house',
    website: 'https://www.posterauctions.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['all_posters', 'advertising', 'travel', 'art_nouveau', 'art_deco'],
    notes: 'Specialized poster auction house. Excellent price history database.',
  },
  {
    name: "L'Affichiste",
    type: 'poster_dealer',
    website: 'https://www.laffichiste.com',
    country: 'France',
    city: 'Paris',
    region: 'France',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.80,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['french', 'advertising', 'art_nouveau', 'belle_epoque'],
    notes: 'Paris-based dealer specializing in French vintage posters.',
  },
  {
    name: 'Galerie 123',
    type: 'poster_dealer',
    website: 'https://www.galerie123.com',
    country: 'France',
    city: 'Paris',
    region: 'France',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.80,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['french', 'advertising', 'art_deco', 'travel'],
    notes: 'French gallery with large inventory of original vintage posters.',
  },
  {
    name: 'Film Art Gallery',
    type: 'poster_dealer',
    website: 'https://www.filmartgallery.com',
    country: 'United States',
    city: 'Los Angeles',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['movie_posters', 'entertainment'],
    notes: 'LA-based vintage movie poster specialist.',
  },
  {
    name: 'Ross Art Group',
    type: 'poster_dealer',
    website: 'https://www.rossartgroup.com',
    country: 'United States',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['movie_posters', 'advertising', 'entertainment'],
    notes: 'Respected poster dealer. Good for movie posters and advertising.',
  },
  {
    name: "Ewbank's",
    type: 'auction_house',
    website: 'https://www.ewbankauctions.co.uk',
    country: 'United Kingdom',
    city: 'Surrey',
    region: 'UK',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['movie_posters', 'entertainment', 'british'],
    notes: 'UK auction house with strong entertainment memorabilia and movie poster sales.',
  },

  // ============================================================
  // TIER 2: Book Dealers
  // ============================================================
  {
    name: 'Bauman Rare Books',
    type: 'book_dealer',
    website: 'https://www.baumanrarebooks.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['illustrated_books', 'rare_books'],
    notes: 'Premier rare book dealer. Excellent for illustrated and antiquarian books.',
  },
  {
    name: 'Peter Harrington',
    type: 'book_dealer',
    website: 'https://www.peterharrington.co.uk',
    country: 'United Kingdom',
    city: 'London',
    region: 'UK',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['illustrated_books', 'rare_books'],
    notes: 'One of the largest rare book dealers in Europe.',
  },
  {
    name: 'Bromer Booksellers',
    type: 'book_dealer',
    website: 'https://www.bromer.com',
    country: 'United States',
    city: 'Boston',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['illustrated_books', 'miniature_books'],
    notes: 'Specialists in miniature books and illustrated books.',
  },
  {
    name: 'Shapero Rare Books',
    type: 'book_dealer',
    website: 'https://www.shapero.com',
    country: 'United Kingdom',
    city: 'London',
    region: 'UK',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['illustrated_books', 'travel', 'natural_history', 'maps'],
    notes: 'Strong in travel books, natural history, and fine illustrated books.',
  },

  // ============================================================
  // TIER 2: Print Dealers
  // ============================================================
  {
    name: 'The Old Print Shop',
    type: 'print_dealer',
    website: 'https://www.oldprintshop.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.oldprintshop.com/search?q={query}',
    specializations: ['american', 'maps', 'natural_history', 'botanical', 'prints'],
    notes: 'One of the oldest print dealers in America. Excellent for American prints and maps.',
  },
  {
    name: 'Arader Galleries',
    type: 'print_dealer',
    website: 'https://www.aradergalleries.com',
    country: 'United States',
    city: 'Philadelphia',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['maps', 'natural_history', 'ornithology', 'botanical'],
    notes: 'Major dealer in antique maps and natural history prints. Multiple gallery locations.',
  },
  {
    name: 'Donald Heald Rare Books',
    type: 'print_dealer',
    website: 'https://www.donaldheald.com',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.85,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['natural_history', 'botanical', 'maps', 'prints', 'rare_books'],
    notes: 'Specializes in natural history, Americana, and fine illustrated books.',
  },

  // ============================================================
  // TIER 2: Map Dealers
  // ============================================================
  {
    name: 'Barry Lawrence Ruderman',
    type: 'map_dealer',
    website: 'https://www.raremaps.com',
    country: 'United States',
    city: 'La Jolla',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.90,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.raremaps.com/search?q={query}',
    specializations: ['maps', 'atlases'],
    notes: 'One of the premier antique map dealers. Extensive research resources on their website.',
  },
  {
    name: 'Old World Auctions',
    type: 'map_dealer',
    website: 'https://www.oldworldauctions.com',
    country: 'United States',
    city: 'Richmond',
    region: 'North America',
    reliabilityTier: 2,
    attributionWeight: 0.85,
    pricingWeight: 0.90,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    specializations: ['maps', 'atlases'],
    notes: 'Specialized antique map auction house. Good price history database.',
  },

  // ============================================================
  // TIER 3: Museums/Institutions (research only)
  // ============================================================
  {
    name: 'Library of Congress',
    type: 'museum',
    website: 'https://www.loc.gov',
    country: 'United States',
    city: 'Washington D.C.',
    region: 'North America',
    reliabilityTier: 3,
    attributionWeight: 0.95,
    pricingWeight: 0.50,
    canResearch: true,
    canPrice: false,
    canProcure: false,
    canBeSource: false,
    searchUrlTemplate: 'https://www.loc.gov/search/?q={query}',
    specializations: ['wwi', 'wwii', 'propaganda', 'maps', 'american'],
    notes: 'Massive digital collection of war posters, maps, and prints. Excellent for attribution research.',
  },
  {
    name: 'MoMA',
    type: 'museum',
    website: 'https://www.moma.org',
    country: 'United States',
    city: 'New York',
    region: 'North America',
    reliabilityTier: 3,
    attributionWeight: 0.95,
    pricingWeight: 0.50,
    canResearch: true,
    canPrice: false,
    canProcure: false,
    canBeSource: false,
    searchUrlTemplate: 'https://www.moma.org/search?query={query}',
    specializations: ['fine_art', 'advertising', 'modernist'],
    notes: 'Museum of Modern Art. Online collection includes posters and graphic design.',
  },
  {
    name: 'Victoria & Albert Museum',
    type: 'museum',
    website: 'https://www.vam.ac.uk',
    country: 'United Kingdom',
    city: 'London',
    region: 'UK',
    reliabilityTier: 3,
    attributionWeight: 0.95,
    pricingWeight: 0.50,
    canResearch: true,
    canPrice: false,
    canProcure: false,
    canBeSource: false,
    searchUrlTemplate: 'https://collections.vam.ac.uk/search/?q={query}',
    specializations: ['advertising', 'art_nouveau', 'victorian', 'british'],
    notes: 'World-leading museum of art and design. Strong poster collection.',
  },
  {
    name: 'Boston Public Library',
    type: 'museum',
    website: 'https://www.bpl.org',
    country: 'United States',
    city: 'Boston',
    region: 'North America',
    reliabilityTier: 3,
    attributionWeight: 0.90,
    pricingWeight: 0.50,
    canResearch: true,
    canPrice: false,
    canProcure: false,
    canBeSource: false,
    specializations: ['maps', 'prints', 'american'],
    notes: 'Excellent digital collections including maps and historical prints.',
  },

  // ============================================================
  // TIER 4: General Marketplaces
  // ============================================================
  {
    name: 'Ruby Lane',
    type: 'marketplace',
    website: 'https://www.rubylane.com',
    country: 'United States',
    region: 'North America',
    reliabilityTier: 4,
    attributionWeight: 0.70,
    pricingWeight: 0.70,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.rubylane.com/search?q={query}',
    specializations: ['general_vintage', 'decorative'],
    notes: 'Curated vintage marketplace. Quality varies by seller but generally reliable.',
  },
  {
    name: '1stDibs',
    type: 'marketplace',
    website: 'https://www.1stdibs.com',
    country: 'United States',
    city: 'New York',
    region: 'Global',
    reliabilityTier: 4,
    attributionWeight: 0.75,
    pricingWeight: 0.75,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.1stdibs.com/search/?q={query}',
    specializations: ['fine_art', 'decorative', 'advertising'],
    notes: 'High-end design marketplace. Premium sellers, higher price points.',
  },

  // ============================================================
  // TIER 5: Aggregators
  // ============================================================
  {
    name: 'LiveAuctioneers',
    type: 'aggregator',
    website: 'https://www.liveauctioneers.com',
    region: 'Global',
    reliabilityTier: 5,
    attributionWeight: 0.65,
    pricingWeight: 0.75,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.liveauctioneers.com/search/?keyword={query}',
    searchSoldUrlTemplate: 'https://www.liveauctioneers.com/price-guide/?keyword={query}',
    specializations: ['all_auctions'],
    notes: 'Major auction aggregator. Good for price research across many auction houses.',
  },
  {
    name: 'Invaluable',
    type: 'aggregator',
    website: 'https://www.invaluable.com',
    region: 'Global',
    reliabilityTier: 5,
    attributionWeight: 0.65,
    pricingWeight: 0.75,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.invaluable.com/search?query={query}',
    specializations: ['all_auctions'],
    notes: 'Major auction aggregator. Extensive price history database.',
  },
  {
    name: 'Barnebys',
    type: 'aggregator',
    website: 'https://www.barnebys.com',
    region: 'Global',
    reliabilityTier: 5,
    attributionWeight: 0.65,
    pricingWeight: 0.70,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.barnebys.com/search/?q={query}',
    specializations: ['all_auctions'],
    notes: 'Auction aggregator with strong European coverage.',
  },
  {
    name: 'AbeBooks',
    type: 'aggregator',
    website: 'https://www.abebooks.com',
    region: 'Global',
    reliabilityTier: 5,
    attributionWeight: 0.65,
    pricingWeight: 0.70,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.abebooks.com/servlet/SearchResults?kn={query}',
    specializations: ['books', 'prints', 'maps', 'ephemera'],
    notes: 'Major book marketplace aggregator. Quality varies by seller.',
  },
  {
    name: 'Biblio',
    type: 'aggregator',
    website: 'https://www.biblio.com',
    region: 'Global',
    reliabilityTier: 5,
    attributionWeight: 0.65,
    pricingWeight: 0.70,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.biblio.com/search?query={query}',
    specializations: ['books', 'prints'],
    notes: 'Book marketplace aggregator. Good for rare and antiquarian books.',
  },

  // ============================================================
  // TIER 6: General Sites (lower reliability)
  // ============================================================
  {
    name: 'eBay',
    type: 'marketplace',
    website: 'https://www.ebay.com',
    region: 'Global',
    reliabilityTier: 6,
    attributionWeight: 0.55,
    pricingWeight: 0.60,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={query}',
    searchSoldUrlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={query}&LH_Complete=1&LH_Sold=1',
    specializations: ['all'],
    notes: 'Largest general marketplace. Useful for price research on sold items. Attribution reliability varies widely.',
  },
  {
    name: 'Etsy',
    type: 'marketplace',
    website: 'https://www.etsy.com',
    region: 'Global',
    reliabilityTier: 6,
    attributionWeight: 0.50,
    pricingWeight: 0.55,
    canResearch: true,
    canPrice: true,
    canProcure: true,
    canBeSource: true,
    searchUrlTemplate: 'https://www.etsy.com/search?q={query}',
    specializations: ['general_vintage', 'decorative'],
    notes: 'Vintage and handmade marketplace. Many reproduction items mixed with genuine vintage.',
  },
];

/**
 * Get count of dealers by tier
 */
export function getDealerCountByTier(): Record<number, number> {
  const counts: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 };
  for (const dealer of DEFAULT_DEALERS) {
    const tier = dealer.reliabilityTier ?? 3;
    counts[tier] = (counts[tier] || 0) + 1;
  }
  return counts;
}

/**
 * Get dealers filtered by type
 */
export function getDefaultDealersByType(type: string): CreateDealerInput[] {
  return DEFAULT_DEALERS.filter(d => d.type === type);
}

/**
 * Get dealers filtered by specialization
 */
export function getDefaultDealersBySpecialization(specialization: string): CreateDealerInput[] {
  return DEFAULT_DEALERS.filter(d => d.specializations?.includes(specialization as any));
}
